CREATE TABLE publication (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    picture VARCHAR(255) NOT NULL,
    description TEXT,
    datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_published BOOLEAN NOT NULL
);

ALTER TABLE votre_table
MODIFY COLUMN is_published TINYINT(1) NOT NULL DEFAULT 0;
